<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="AddInException.xml" source-language="en-US" target-language="zh-CN">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-38f25dd" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">b4690f9a-9e49-426d-9091-855b10fda4db02031ae27d8140e8773a2e496d35b7acffca9f03.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02031ae27d8140e8773a2e496d35b7acffca9f03</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">bb8a3a96823cedeffbdbcc0c41a8118399de8074</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02/21/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">vsto-2017</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:Microsoft.VisualStudio.Tools.Applications.Runtime.AddInException">
          <source>The exception that is thrown when an exception is passed between an add-in and the host application.</source>
          <target state="translated">当在加载项与主机应用程序之间传递异常时引发的异常。</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:Microsoft.VisualStudio.Tools.Applications.Runtime.AddInException">
          <source>If a proxy exception has not been mapped for the original exception, the <ph id="ph1">&lt;xref:System.Exception.Message%2A&gt;</ph> property of an <ph id="ph2">&lt;xref:Microsoft.VisualStudio.Tools.Applications.Runtime.AddInException&gt;</ph> contains the fully qualified type name of the original exception, followed by the fully qualified type names of each of the inner exceptions, and finally the text returned by the <ph id="ph3">&lt;xref:System.Exception.ToString%2A&gt;</ph> method of the original exception.</source>
          <target state="translated">如果尚未为原始异常，映射代理异常<ph id="ph1">&lt;xref:System.Exception.Message%2A&gt;</ph>属性<ph id="ph2">&lt;xref:Microsoft.VisualStudio.Tools.Applications.Runtime.AddInException&gt;</ph>包含原始异常，每个内部异常，异常的完全限定的类型名称后跟的完全限定的类型名称和最后返回的文本<ph id="ph3">&lt;xref:System.Exception.ToString%2A&gt;</ph>的原始异常的方法。</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:Microsoft.VisualStudio.Tools.Applications.Runtime.AddInException">
          <source>Otherwise, if a proxy exception has been mapped for the original exception, the proxy exception is thrown.</source>
          <target state="translated">否则，如果代理异常已映射为原始异常，会引发代理异常。</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" uid="M:Microsoft.VisualStudio.Tools.Applications.Runtime.AddInException.#ctor(System.Exception)">
          <source>The <ph id="ph1">&lt;see cref="T:System.Exception" /&gt;</ph> that is the cause of the current exception, or <ph id="ph2">&lt;see langword="null" /&gt;</ph> if no inner exception is specified.</source>
          <target state="translated">导致当前异常的 <ph id="ph1">&lt;see cref="T:System.Exception" /&gt;</ph>，或者如果没有指定内部异常，则为 <ph id="ph2">&lt;see langword="null" /&gt;</ph>。</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" uid="M:Microsoft.VisualStudio.Tools.Applications.Runtime.AddInException.#ctor(System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:Microsoft.VisualStudio.Tools.Applications.Runtime.AddInException" /&gt;</ph> class with a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">用对作为此异常原因的内部异常的引用初始化 <ph id="ph1">&lt;see cref="T:Microsoft.VisualStudio.Tools.Applications.Runtime.AddInException" /&gt;</ph> 类的新实例。</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" uid="M:Microsoft.VisualStudio.Tools.Applications.Runtime.AddInException.System#Runtime#Serialization#ISerializable#GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>A <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> that contains the information that is required to serialize the current <ph id="ph2">&lt;see cref="T:Microsoft.VisualStudio.Tools.Applications.Runtime.AddInException" /&gt;</ph>.</source>
          <target state="translated"><ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph>，它包含序列化当前 <ph id="ph2">&lt;see cref="T:Microsoft.VisualStudio.Tools.Applications.Runtime.AddInException" /&gt;</ph> 所需的信息。</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" uid="M:Microsoft.VisualStudio.Tools.Applications.Runtime.AddInException.System#Runtime#Serialization#ISerializable#GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>A <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph> that contains the source and destination of the serialized stream that is associated with the current <ph id="ph2">&lt;see cref="T:Microsoft.VisualStudio.Tools.Applications.Runtime.AddInException" /&gt;</ph>.</source>
          <target state="translated"><ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph>，它包含与当前 <ph id="ph2">&lt;see cref="T:Microsoft.VisualStudio.Tools.Applications.Runtime.AddInException" /&gt;</ph> 关联的序列化流的源和目标。</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" uid="M:Microsoft.VisualStudio.Tools.Applications.Runtime.AddInException.System#Runtime#Serialization#ISerializable#GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Adds information about the exception to the specified <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph>.</source>
          <target state="translated">将有关异常的信息添加到指定 <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph>。</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>