<Type Name="ErrorAddDataBoundRowEventArgs" FullName="Microsoft.Office.Tools.Excel.ErrorAddDataBoundRowEventArgs">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="018b6377ebcf058e3a74c0091371a756b82e61b1" />
    <Meta Name="ms.sourcegitcommit" Value="bb8a3a96823cedeffbdbcc0c41a8118399de8074" />
    <Meta Name="ms.translationtype" Value="HT" />
    <Meta Name="ms.contentlocale" Value="zh-CN" />
    <Meta Name="ms.lasthandoff" Value="02/21/2018" />
    <Meta Name="ms.locfileid" Value="29431177" />
  </Metadata>
  <TypeSignature Language="C#" Value="public interface ErrorAddDataBoundRowEventArgs" />
  <TypeSignature Language="ILAsm" Value=".class public interface auto ansi abstract ErrorAddDataBoundRowEventArgs" />
  <TypeSignature Language="DocId" Value="T:Microsoft.Office.Tools.Excel.ErrorAddDataBoundRowEventArgs" />
  <AssemblyInfo>
    <AssemblyName>Microsoft.Office.Tools.Excel</AssemblyName>
    <AssemblyVersion>10.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Interfaces />
  <Attributes>
    <Attribute>
      <AttributeName>System.Runtime.InteropServices.Guid("eca34a5d-a43c-4be4-a24a-49d49ae4519b")</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary>
      <span data-ttu-id="5503a-101">提供有关 <see cref="E:Microsoft.Office.Tools.Excel.ListObject.ErrorAddDataBoundRow" /> 事件的信息。</span>
      <span class="sxs-lookup">
        <span data-stu-id="5503a-101">Provides information for the <see cref="E:Microsoft.Office.Tools.Excel.ListObject.ErrorAddDataBoundRow" /> event.</span>
      </span>
    </summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="5503a-102"><xref:Microsoft.Office.Tools.Excel.ListObject.ErrorAddDataBoundRow>事件由引发<xref:Microsoft.Office.Tools.Excel.ListObject>如果尝试将新行添加到数据源过程中发生异常的控件绑定到<xref:Microsoft.Office.Tools.Excel.ListObject>。</span><span class="sxs-lookup"><span data-stu-id="5503a-102">The <xref:Microsoft.Office.Tools.Excel.ListObject.ErrorAddDataBoundRow> event is raised by the <xref:Microsoft.Office.Tools.Excel.ListObject> control if an exception occurs during an attempt to add a new row to the data source bound to the <xref:Microsoft.Office.Tools.Excel.ListObject>.</span></span> <span data-ttu-id="5503a-103"><xref:Microsoft.Office.Tools.Excel.ErrorAddDataBoundRowEventArgs.Item%2A>属性可以用于获取新项<xref:Microsoft.Office.Tools.Excel.ListObject>尝试添加。</span><span class="sxs-lookup"><span data-stu-id="5503a-103">The <xref:Microsoft.Office.Tools.Excel.ErrorAddDataBoundRowEventArgs.Item%2A> property can be used to get the new item that the <xref:Microsoft.Office.Tools.Excel.ListObject> tried to add.</span></span> <span data-ttu-id="5503a-104"><xref:Microsoft.Office.Tools.Excel.ErrorAddDataBoundRowEventArgs.InnerException%2A>属性提供已引发的异常和<xref:Microsoft.Office.Tools.Excel.ErrorAddDataBoundRowEventArgs.Retry%2A>属性可以用于指示是否应进行另一个尝试添加此行。</span><span class="sxs-lookup"><span data-stu-id="5503a-104">The <xref:Microsoft.Office.Tools.Excel.ErrorAddDataBoundRowEventArgs.InnerException%2A> property provides the exception that was thrown, and the <xref:Microsoft.Office.Tools.Excel.ErrorAddDataBoundRowEventArgs.Retry%2A> property can be used to indicate whether another attempt to add this row should be made.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="5503a-105">下面的代码示例创建<xref:System.Data.DataTable>和<xref:Microsoft.Office.Tools.Excel.ListObject>，并将绑定<xref:Microsoft.Office.Tools.Excel.ListObject>到<xref:System.Data.DataTable>。</span><span class="sxs-lookup"><span data-stu-id="5503a-105">The following code example creates a <xref:System.Data.DataTable> and a <xref:Microsoft.Office.Tools.Excel.ListObject>, and binds the <xref:Microsoft.Office.Tools.Excel.ListObject> to the <xref:System.Data.DataTable>.</span></span> <span data-ttu-id="5503a-106">然后，它创建<xref:Microsoft.Office.Tools.Excel.ListObject.ErrorAddDataBoundRow>事件处理程序。</span><span class="sxs-lookup"><span data-stu-id="5503a-106">It then creates an <xref:Microsoft.Office.Tools.Excel.ListObject.ErrorAddDataBoundRow> event handler.</span></span> <span data-ttu-id="5503a-107">若要测试事件，手动向其中添加新行<xref:Microsoft.Office.Tools.Excel.ListObject>输入姓氏"通道"和第一个名称。</span><span class="sxs-lookup"><span data-stu-id="5503a-107">To test the event, manually add a new row to the <xref:Microsoft.Office.Tools.Excel.ListObject> and enter the last name "Chan" and a first name.</span></span> <span data-ttu-id="5503a-108">事件处理程序会显示一条消息。</span><span class="sxs-lookup"><span data-stu-id="5503a-108">The event handler displays a message.</span></span>  
  
 <span data-ttu-id="5503a-109">此示例适用于文档级自定义。</span><span class="sxs-lookup"><span data-stu-id="5503a-109">This example is for a document-level customization.</span></span>  
  
 [!code-csharp[Trin_ExcelListObject#20](~/snippets/csharp/VS_Snippets_OfficeSP/Trin_ExcelListObject/CS/Trin_ExcelListObject.cs#20)]
 [!code-vb[Trin_ExcelListObject#20](~/snippets/visualbasic/VS_Snippets_OfficeSP/Trin_ExcelListObject/VB/Sheet1.vb#20)]  
  
 ]]></format>
    </remarks>
  </Docs>
  <Members>
    <Member MemberName="InnerException">
      <MemberSignature Language="C#" Value="public Exception InnerException { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Exception InnerException" />
      <MemberSignature Language="DocId" Value="P:Microsoft.Office.Tools.Excel.ErrorAddDataBoundRowEventArgs.InnerException" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Office.Tools.Excel</AssemblyName>
        <AssemblyVersion>10.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Exception</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
          <span data-ttu-id="5503a-110">获取导致当前异常的 <see cref="T:System.Exception" /> 实例。</span>
          <span class="sxs-lookup">
            <span data-stu-id="5503a-110">Gets the <see cref="T:System.Exception" /> instance that caused the current exception.</span>
          </span>
        </summary>
        <value>
          <span data-ttu-id="5503a-111">一个 <see cref="T:System.Exception" /> 的实例，描述导致当前异常的错误。</span>
          <span class="sxs-lookup">
            <span data-stu-id="5503a-111">An instance of <see cref="T:System.Exception" /> that describes the error that caused the current exception.</span>
          </span>
        </value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="5503a-112"><xref:Microsoft.Office.Tools.Excel.ListObject.ErrorAddDataBoundRow>作为尝试将新行添加到数据源时出现异常的直接结果引发事件。</span><span class="sxs-lookup"><span data-stu-id="5503a-112">The <xref:Microsoft.Office.Tools.Excel.ListObject.ErrorAddDataBoundRow> event is raised as a direct result of an exception while attempting to add a new row to the data source.</span></span> <span data-ttu-id="5503a-113">使用<xref:Microsoft.Office.Tools.Excel.ErrorAddDataBoundRowEventArgs.InnerException%2A>属性来获取与此错误引发的异常。</span><span class="sxs-lookup"><span data-stu-id="5503a-113">Use the <xref:Microsoft.Office.Tools.Excel.ErrorAddDataBoundRowEventArgs.InnerException%2A> property to obtain the exception that led to this error.</span></span> <span data-ttu-id="5503a-114">例如，如果<xref:System.Data.DataTable>，它绑定到<xref:Microsoft.Office.Tools.Excel.ListObject>控件不允许将一个列`null`，和用户未指定此列的值，尝试将该行添加导致<xref:System.Data.NoNullAllowedException>被引发。</span><span class="sxs-lookup"><span data-stu-id="5503a-114">For example, if the <xref:System.Data.DataTable> that is bound to the <xref:Microsoft.Office.Tools.Excel.ListObject> control does not allow a column to be `null`, and the user does not specify a value for this column, the attempt to add the row causes a <xref:System.Data.NoNullAllowedException> to be raised.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="Item">
      <MemberSignature Language="C#" Value="public object Item { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance object Item" />
      <MemberSignature Language="DocId" Value="P:Microsoft.Office.Tools.Excel.ErrorAddDataBoundRowEventArgs.Item" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Office.Tools.Excel</AssemblyName>
        <AssemblyVersion>10.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Object</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
          <span data-ttu-id="5503a-115">获取 <see cref="T:Microsoft.Office.Tools.Excel.ListObject" /> 尝试添加到数据源的新项。</span>
          <span class="sxs-lookup">
            <span data-stu-id="5503a-115">Gets the new item that the <see cref="T:Microsoft.Office.Tools.Excel.ListObject" /> attempted to add to the data source.</span>
          </span>
        </summary>
        <value>
          <span data-ttu-id="5503a-116">要添加的项。</span>
          <span class="sxs-lookup">
            <span data-stu-id="5503a-116">The item to be added.</span>
          </span>
        </value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="5503a-117">当<xref:Microsoft.Office.Tools.Excel.ListObject>绑定到<xref:System.Data.DataTable>，该项应当是<xref:System.Data.DataRowView>而不是<xref:System.Data.DataRow>。</span><span class="sxs-lookup"><span data-stu-id="5503a-117">When the <xref:Microsoft.Office.Tools.Excel.ListObject> is bound to a <xref:System.Data.DataTable>, the item would be a <xref:System.Data.DataRowView> rather than a <xref:System.Data.DataRow>.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="Retry">
      <MemberSignature Language="C#" Value="public bool Retry { get; set; }" />
      <MemberSignature Language="ILAsm" Value=".property instance bool Retry" />
      <MemberSignature Language="DocId" Value="P:Microsoft.Office.Tools.Excel.ErrorAddDataBoundRowEventArgs.Retry" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Office.Tools.Excel</AssemblyName>
        <AssemblyVersion>10.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Boolean</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
          <span data-ttu-id="5503a-118">获取或设置一个值，该值指示 <see cref="T:Microsoft.Office.Tools.Excel.ListObject" /> 是否应该再次尝试添加此项。</span>
          <span class="sxs-lookup">
            <span data-stu-id="5503a-118">Gets or sets a value indicating whether the <see cref="T:Microsoft.Office.Tools.Excel.ListObject" /> should attempt to add the item again.</span>
          </span>
        </summary>
        <value>
          <span data-ttu-id="5503a-119">
            <see langword="true" /> 如果应进行另一个尝试;否则为<see langword="false" />。</span>
          <span class="sxs-lookup">
            <span data-stu-id="5503a-119">
              <see langword="true" /> if another attempt should be made; otherwise, <see langword="false" />.</span>
          </span>
          <span data-ttu-id="5503a-120">默认值为 <see langword="false" />。</span>
          <span class="sxs-lookup">
            <span data-stu-id="5503a-120">The default value is <see langword="false" />.</span>
          </span>
        </value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="5503a-121">如果<xref:Microsoft.Office.Tools.Excel.ListObject>添加新行中，在尝试时遇到错误<xref:Microsoft.Office.Tools.Excel.ListObject.ErrorAddDataBoundRow>引发事件。</span><span class="sxs-lookup"><span data-stu-id="5503a-121">If the <xref:Microsoft.Office.Tools.Excel.ListObject> encounters an error when attempting to add the new row, the <xref:Microsoft.Office.Tools.Excel.ListObject.ErrorAddDataBoundRow> event is raised.</span></span> <span data-ttu-id="5503a-122">开发人员可以处理此事件，并尝试解决出现的任何错误。</span><span class="sxs-lookup"><span data-stu-id="5503a-122">The developer can handle this event and attempt to fix any errors that occur.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>