<Type Name="ListObjectNotDataBoundException" FullName="Microsoft.Office.Tools.Excel.ListObjectNotDataBoundException">
  <Metadata><Meta Name="ms.openlocfilehash" Value="e84d004fa94d9f964f964f0aac35fdf6ed3f9160" /><Meta Name="ms.sourcegitcommit" Value="7439021cdeee6a9ef5d4640250701344f6cbba15" /><Meta Name="ms.translationtype" Value="MT" /><Meta Name="ms.contentlocale" Value="zh-CN" /><Meta Name="ms.lasthandoff" Value="08/13/2019" /><Meta Name="ms.locfileid" Value="69004740" /></Metadata><TypeSignature Language="C#" Value="public sealed class ListObjectNotDataBoundException : Microsoft.VisualStudio.Tools.Applications.Runtime.RuntimeException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable sealed beforefieldinit ListObjectNotDataBoundException extends Microsoft.VisualStudio.Tools.Applications.Runtime.RuntimeException" />
  <TypeSignature Language="DocId" Value="T:Microsoft.Office.Tools.Excel.ListObjectNotDataBoundException" />
  <AssemblyInfo>
    <AssemblyName>Microsoft.Office.Tools.v4.0.Framework</AssemblyName>
    <AssemblyVersion>10.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>Microsoft.VisualStudio.Tools.Applications.Runtime.RuntimeException</BaseTypeName>
  </Base>
  <Interfaces />
  <Attributes>
    <Attribute>
      <AttributeName>System.Diagnostics.DebuggerNonUserCode</AttributeName>
    </Attribute>
    <Attribute>
      <AttributeName>System.Serializable</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary><span data-ttu-id="6f5f3-101">使用未绑定到数据的 <see cref="T:Microsoft.Office.Tools.Excel.ListObject" /> 的 <see cref="M:Microsoft.Office.Tools.Excel.ListObject.Disconnect" /> 方法时引发的异常。</span><span class="sxs-lookup"><span data-stu-id="6f5f3-101">The exception that is thrown when you use the <see cref="M:Microsoft.Office.Tools.Excel.ListObject.Disconnect" /> method of a <see cref="T:Microsoft.Office.Tools.Excel.ListObject" /> that is not bound to data.</span></span></summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="6f5f3-102">方法从中删除数据绑定。 <xref:Microsoft.Office.Tools.Excel.ListObject> <xref:Microsoft.Office.Tools.Excel.ListObject.Disconnect%2A></span><span class="sxs-lookup"><span data-stu-id="6f5f3-102">The <xref:Microsoft.Office.Tools.Excel.ListObject.Disconnect%2A> method removes the data binding from a <xref:Microsoft.Office.Tools.Excel.ListObject>.</span></span>  
  
 ]]></format>
    </remarks>
  </Docs>
  <Members>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public ListObjectNotDataBoundException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:Microsoft.Office.Tools.Excel.ListObjectNotDataBoundException.#ctor" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Office.Tools.v4.0.Framework</AssemblyName>
        <AssemblyVersion>10.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary><span data-ttu-id="6f5f3-103">初始化 <see cref="T:Microsoft.Office.Tools.Excel.ListObjectNotDataBoundException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="6f5f3-103">Initializes a new instance of the <see cref="T:Microsoft.Office.Tools.Excel.ListObjectNotDataBoundException" /> class.</span></span></summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public ListObjectNotDataBoundException (Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:Microsoft.Office.Tools.Excel.ListObjectNotDataBoundException.#ctor(System.Exception)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Office.Tools.v4.0.Framework</AssemblyName>
        <AssemblyVersion>10.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="innerException"><span data-ttu-id="6f5f3-104">导致当前异常的异常。</span><span class="sxs-lookup"><span data-stu-id="6f5f3-104">The exception that is the cause of the current exception.</span></span></param>
        <summary><span data-ttu-id="6f5f3-105">使用导致此异常的内部异常初始化 <see cref="T:Microsoft.Office.Tools.Excel.ListObjectNotDataBoundException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="6f5f3-105">Initializes a new instance of the <see cref="T:Microsoft.Office.Tools.Excel.ListObjectNotDataBoundException" /> class with the inner exception that is the cause of this exception.</span></span></summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public ListObjectNotDataBoundException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:Microsoft.Office.Tools.Excel.ListObjectNotDataBoundException.#ctor(System.String)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Office.Tools.v4.0.Framework</AssemblyName>
        <AssemblyVersion>10.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message"><span data-ttu-id="6f5f3-106">描述错误的消息。</span><span class="sxs-lookup"><span data-stu-id="6f5f3-106">A message that describes the error.</span></span></param>
        <summary><span data-ttu-id="6f5f3-107">用指定的错误消息初始化 <see cref="T:Microsoft.Office.Tools.Excel.ListObjectNotDataBoundException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="6f5f3-107">Initializes a new instance of the <see cref="T:Microsoft.Office.Tools.Excel.ListObjectNotDataBoundException" /> class with a specified error message.</span></span></summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public ListObjectNotDataBoundException (string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:Microsoft.Office.Tools.Excel.ListObjectNotDataBoundException.#ctor(System.String,System.Exception)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Office.Tools.v4.0.Framework</AssemblyName>
        <AssemblyVersion>10.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message"><span data-ttu-id="6f5f3-108">描述错误的消息。</span><span class="sxs-lookup"><span data-stu-id="6f5f3-108">A message that describes the error.</span></span></param>
        <param name="innerException"><span data-ttu-id="6f5f3-109">导致当前异常的异常。</span><span class="sxs-lookup"><span data-stu-id="6f5f3-109">The exception that is the cause of the current exception.</span></span></param>
        <summary><span data-ttu-id="6f5f3-110">使用指定的错误消息和对作为此异常原因的内部异常的引用来初始化 <see cref="T:Microsoft.Office.Tools.Excel.ListObjectNotDataBoundException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="6f5f3-110">Initializes a new instance of the <see cref="T:Microsoft.Office.Tools.Excel.ListObjectNotDataBoundException" /> class with a specified error message and a reference to the inner exception that is the cause of this exception.</span></span></summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
  </Members>
</Type>
